title: Mason's Blog
email: mason@kissr.co
description: >
  Hello! I'm Mason. I like like simipicity, honesty happiness and other good stuff like that. This is my blog about technical stuff and other stuff too.
url: "http://www.masonforest.com"
twitter_username: masonforest
github_username:  masonforest
markdown: kramdown
